<?php

if (true){//ES
    // Menu language
    $Dashboard		    	= "Tablero";
    $Transaction			= "Transacción";
    $Incomes				= "Ingresos";
    $Reports				= "Reportes";
    $ManageBudget			= "Administrar Presupuesto";
    $ManageCategories		= "Administrar Categorías";
    $ManageAccount			= "Administrar Cuenta";
    $Expenses				= "Gastos";
    $Settings				= "Configuración";
    $Logout					= "Cerrar Sesión";
    
    //Pages language
    $Welcome				= "Bienvenido";
    $Name					= "Nombre";
    $Amount					= "Monto";
    $Category				= "Categoría";
    $Account				= "Cuenta";
    $Date					= "Fecha";
    $Description			= "Descripción";
    $HistoryofBudget		= "Historial del Presupuesto";
    $AssetReports			= "Reporte de Activos";
    $HistoryofAssets		= "Historial de Activos";
    $AssetsbyAccount		= "Activos por Cuenta";
    $Action					= "Acción";
    $TotalIncomeThisMonth	= "Total ingresos este mes";
    $TotalIncomeToday		= "Total ingresos hoy";
    $DownloadIncomeReports	= "Descargar Reporte Ingresos";
    $BudgetFor				= "Presupuesto para";
    $BudgetInformation		= "Información Presupuesto";
    $ListCategory			= "Lista de Categorías";
    $AddNewCategory			= "Agregar Categoría";
    $ListAccount			= "Lista de Cuentas";
    $AddAccount				= "Agregar Cuenta";
    $ExpenseReports			= "Reporte de Gastos";
    $HistoryofExpense		= "Historial de Gastos";
    $ExpenseByCategory		= "Gastos por Categoría";
    $TotalExpenseThisMonth  = "Total gastos este mes";
    $TotalExpenseToday		= "Total gastos hoy";
    $DownloadExpenseReports = "Descargar Reporte Gastos";
    $DownloadExpenseCSV 	= "Descargar Reporte Gastos CSV";
    $DownloadIncomeCSV 		= "Descargar Reporte Ingresos CSV";
    $ChangeAccountProfile	= "Modificar Perfil";
    $Emails					= "Correo";
    $Currencys				= "Moneda";
    $CreateAnAccount		= "Crear Cuenta";
    $UserSign				= "Iniciar Sesión";
    $FirstNames				= "Nombre";
    $LastNames				= "Apellido";
    $Passwords				= "Contraseña";
    $RepeatPassword			= "Repitir Contraseña";
    $BudgetProgressOn		= "Progreso del Presupuesto";
    $Out					= "Salida";
    $Outs					= "Salidas";
    $RemainingBudget		= "Presupuesto Disponible";
    $CurrentExpense			= "Gastos Actuales Este Mes";
    $CurrentIncome			= "Ingresos Actuales Este Mes";
    $TotalExpenseDashboard  = "Total Gastos";
    $CurrentBalance			= "Balance Total Actual";
    $TenIncome				= "Últimos 10 Ingresos";
    $TenExpense				= "Últimos 10 Egresos";
    $Title					= "Título";
    $Amounts				= "Cantidades";
    $Exceeds				= "Excedentes";
    $ReportsExpenseIncome	= "Reportes Gastos/Ingresos";
    $ReportsExpenseIncomeM	= "Reporte Gastos/Ingresos Este Mes";
    $BudgetForCategory		= "Presupuesto por Categoría";
    $Search					= "Buscar...";
    $AccountMessage			= "<h4>Alerta!</h4> La cantidad de esta cuenta se eliminará de la base de datos.";
    $ManageExpense			= "Administrar Gastos";
    $ManageIncome			= "Administrar Ingresos";
    $Budgetss				= "Presupuesto";
    $IncomeVsExpense		= "Ingresos Vs Gastos";
    $OverallReport			= "Reporte General";
    $ReportByMonth			= "Reporte Mensual";
    $ReportByDay			= "Reporte Diario";
    $ReportTotalIncome		= "Ingreso Total :";
    $ReportTotalExpense		= "Gasto Total :";
    $ReportIncomeExpense	= "Ingresos - Gastos :";
    $Today 					= "Hoy";
    $Months 				= "Mes";
    $Overall 				= "General";
    $CalenderIncome			= "Calenderio de Ingresos";
    $CalenderExpense		= "Calendario de Gastos";
    
    //MessageBox
    $AreYouSure				= "¿Desea eliminar este elemento?";
    $ThisItem				= "Este elemento será eliminado de la base de datos.";
    $EditThisCategory		= "¿Editar esta Categoría?";
    $EditThisAccount		= "¿Editar esta Cuenta?";
    $EditThisBudget			= "¿Editar este Presupuesto?";
    $CategoryIncome			= "Categorías de Ingresos";
    $CategoryExpense		= "Categorías de Gastos";
    $ProfileSettings		= "Configuración de Perfil";
    $ReportsGraphs			= "Reportes & Gráficos";
    $IncomeReportsM 		= "Reportes de Ingresos";
    $ExpenseReportsM		= "Reportes de Gastos";
    $BudgetsM				= "Presupuestos";
    $AccountBalance			= "Balance de Cuenta";
    $NewTransaction			= "Nueva Transacción";
    $NewAccount				= "Nueva Cuenta";
    $ManageCategoriesIncome	= "Administrar Categorías de Ingresos";
    $ManageCategoriesExpense= "Administrar Categorías de Gastos";
    $NewBudgets				= "Agregar Presupuesto";
    $Amounts 				= "Montos";
    $IncomeCalender			= "Calendario Ingresos";
    $ExpenseCalender		= "Calendario Gastos";
    $IncomeSummary			= "Resumen Ingresos";
    $ExpenseSummary			= "Resumen Gastos";
    
    //For Report
    $TotalExpenseReport		= "Total Gastos: "; 
    $TotalIncomeReport		= "Total Ingresos: "; 
    
    //Button for all pages
    $Yes					= "Sí";
    $Save					= "Guardar";
    $Cancel					= "Cancelar";
    $RegisterAnAccount		= "Registrar Cuenta";
    $SignIn					= "Ingresar";
    $SaveIncome				= "Guardar Ingreso";
    $EditIncome				= "Editar Ingreso";
    $DeleteIncomes			= "Eliminar Ingreso";
    $SaveExpense			= "Guardar Gasto";
    $EditExpense			= "Editar Gasto";
    $DeleteExpenses			= "Eliminar Gasto";
    $SaveBudget				= "Guardar Presupuesto";
    $EditBudget				= "Editar Presupuesto";
    $DeleteBudgets			= "Eliminar Presupuesto";
    $SaveCategory			= "Guardar Categoría";
    $EditCategory			= "Editar Categoría";
    $DeleteCategories		= "Eliminar Categoría";
    $SaveAccount			= "Guardar Cuenta";
    $EditAccount			= "Editar Cuenta";
    $DeleteAccounts			= "Eliminar Cuenta";
    $ViewDetails			= "Ver Detalles";
    
    //notification message for all pages
    $SaveMsgIncome			= "Ingreso guardado correctamente";
    $UpdateMsgIncome		= "Ingreso actualizado correctamente";
    $UpdateMsgExpense		= "Gasto actualizado correctamente";
    $SaveMsgExpense			= "Gasto guardado correctamente";
    $LoginError				= "Ingreso fallido, valide credenciales.";
    $EmailEmpty				= "Por favor, ingrese su correo.";
    $PasswordEmpty			= "Por favor, ingrese su contraseña.";
    $SignUpEmpty			= "Todos los campos son requeridos.";
    $PwdNotSame				= "Valores de la contraseña no coinciden.";
    $SuccessAccount			= "Cuenta creada correctamente, por favor " .'<a href="login.php">¡Inicie Sesión!</a>';
    $AlreadyRegister		= "Cuenta ya registrada, por favor " .'<a href="login.php">¡Inicie Sesión!</a>';
    $SuccessAccountUpdate	= "Cuenta actualizada correctamente.";
    $DeleteIncome			= "Ingreso eliminado correctamente.";
    $DeleteCategory			= "Categoría eliminada correctamente.";
    $SaveMsgCategory		= "Categoría guardada correctamente.";
    $UpdateMsgCategory		= "Categoría actualizada correctamente.";
    $DeleteAccount			= "Cuenta eliminada correctamente.";
    $SaveMsgAccount			= "Cuenta guardada correctamente.";
    $UpdateMsgAccount		= "Cuenta actualizada correctamente.";
    $SaveMsgBudget			= "Presupuesto actualizado correctamente.";
    $AlreadyBudget			= "¡Disculpas! Presupuesto para esta categoría ya ha sido registrado.";
    $DeleteBudget			= "Presupuesto eliminado correctamente.";
    $UpdateMsgBudget		= "Presupuesto actualizado correctamente.";
    $DeleteExpense			= "Gasto ha sido eliminado correctamente.";
    $NegativeAmount			= "Cantidades negativas no son permitidas.";
    $MessageEmpty			= "Algún campo es requerido.";
    
}else{//EN

    // Menu language
    $Dashboard		    	= "Dashboard";
    $Transaction			= "Transaction";
    $Incomes				= "Incomes";
    $Reports				= "Reports";
    $ManageBudget			= "Manage Budget";
    $ManageCategories		= "Manage Categories";
    $ManageAccount			= "Manage Account";
    $Expenses				= "Expenses";
    $Settings				= "Settings";
    $Logout					= "Logout";

    //Pages language
    $Welcome				= "Welcome";
    $Name					= "Name";
    $Amount					= "Amount";
    $Category				= "Category";
    $Account				= "Account";
    $Date					= "Date";
    $Description			= "Description";
    $HistoryofBudget		= "History of Budget";
    $AssetReports			= "Assets Reports";
    $HistoryofAssets		= "History of Assets";
    $AssetsbyAccount		= "Assets by Account";
    $Action					= "Action";
    $TotalIncomeThisMonth	= "Total Income this month";
    $TotalIncomeToday		= "Total Income Today";
    $DownloadIncomeReports	= "Download Income Reports";
    $BudgetFor				= "Budget for";
    $BudgetInformation		= "Budget Information";
    $ListCategory			= "List Category";
    $AddNewCategory			= "Add New Category";
    $ListAccount			= "List Account";
    $AddAccount				= "Add New Account";
    $ExpenseReports			= "Expense Reports";
    $HistoryofExpense		= "History of Expense";
    $ExpenseByCategory		= "Expense By Category";
    $TotalExpenseThisMonth  = "Total Expense this month";
    $TotalExpenseToday		= "Total Expense Today";
    $DownloadExpenseReports = "Download Expense Reports";
    $DownloadExpenseCSV 	= "Download Expense CSV";
    $DownloadIncomeCSV 		= "Download Income CSV";
    $ChangeAccountProfile	= "Change Account Profile";
    $Emails					= "Email";
    $Currencys				= "Currency";
    $CreateAnAccount		= "Create An Account";
    $UserSign				= "User Sign In";
    $FirstNames				= "First Name";
    $LastNames				= "Last Name";
    $Passwords				= "Password";
    $RepeatPassword			= "Repeat Password";
    $BudgetProgressOn		= "Budget Progress On";
    $Out					= "Out";
    $Outs					= "Out";
    $RemainingBudget		= "Remaining Budget";
    $CurrentExpense			= "Current Expense This Month";
    $CurrentIncome			= "Current Income This Month";
    $TotalExpenseDashboard  = "Your Total Expense";
    $CurrentBalance			= "Your Current Total Balance";
    $TenIncome				= "Latest 10 Income";
    $TenExpense				= "Latest 10 Expense";
    $Title					= "Title";
    $Amounts				= "Amount";
    $Exceeds				= "Over Budget";
    $ReportsExpenseIncome	= "Reports Expense/Income";
    $ReportsExpenseIncomeM	= "Report Expense/Income This Month";
    $BudgetForCategory		= "Budget for Category";
    $Search					= "Search...";
    $AccountMessage			= "<h4>Warning!</h4> Amount on this Account will delete from database.";
    $ManageExpense			= "Manage Expense";
    $ManageIncome			= "Manage Income";
    $Budgetss				= "Budget";
    $IncomeVsExpense		= "Income Vs Expense";
    $OverallReport			= "Overall Report";
    $ReportByMonth			= "Report This Month";
    $ReportByDay			= "Report Today";
    $ReportTotalIncome		= "Total Income :";
    $ReportTotalExpense		= "Total Expense :";
    $ReportIncomeExpense	= "Income - Expense :";
    $Today 					= "Today";
    $Months 				= "Month";
    $Overall 				= "Overall";
    $CalenderIncome			= "Income Calender";
    $CalenderExpense		= "Expense Calender";

    //MessageBox
    $AreYouSure				= "Are you sure to delete this item?";
    $ThisItem				= "This Item will remove from database history.";
    $EditThisCategory		= "Edit this Category?";
    $EditThisAccount		= "Edit this Account?";
    $EditThisBudget			= "Edit this Budget?";
    $CategoryIncome			= "Income Categories";
    $CategoryExpense		= "Expense Categories";
    $ProfileSettings		= "Profile Settings";
    $ReportsGraphs			= "Reports & Graphs";
    $IncomeReportsM 		= "Income Reports";
    $ExpenseReportsM		= "Expense Reports";
    $BudgetsM				= "Budgets";
    $AccountBalance			= "Account Balances";
    $NewTransaction			= "New Transaction";
    $NewAccount				= "New Account";
    $ManageCategoriesIncome	= "Manage Income Categories";
    $ManageCategoriesExpense	= "Manage Expense Categories";
    $NewBudgets				= "Add New Budget";
    $Amounts 				= "Amount";
    $IncomeCalender			= "Income Calender";
    $ExpenseCalender		= "Expense Calender";
    $IncomeSummary			= "Incomes Summary";
    $ExpenseSummary			= "Expense Summary";

    //For Report
    $TotalExpenseReport		= "Total Expense: "; 
    $TotalIncomeReport		= "Total Income: "; 

    //Button for all pages
    $Yes					= "Yes";
    $Save					= "Save";
    $Cancel					= "Cancel";
    $RegisterAnAccount		= "Register An Account";
    $SignIn					= "Sign In";
    $SaveIncome				= "Save Income";
    $EditIncome				= "Edit Income";
    $DeleteIncomes			= "Delete Income";
    $SaveExpense			= "Save Expense";
    $EditExpense			= "Edit Expense";
    $DeleteExpenses			= "Delete Expense";
    $SaveBudget				= "Save Budget";
    $EditBudget				= "Edit Budget";
    $DeleteBudgets			= "Delete Budget";
    $SaveCategory			= "Save Category";
    $EditCategory			= "Edit Category";
    $DeleteCategories		= "Delete Category";
    $SaveAccount			= "Save Account";
    $EditAccount			= "Edit Account";
    $DeleteAccounts			= "Delete Account";
    $ViewDetails			= "View Details";

    //notification message for all pages
    $SaveMsgIncome			= "Income has been saved sucessfully";
    $UpdateMsgIncome		= "Income has been updated sucessfully";
    $UpdateMsgExpense		= "Expense has been updated sucessfully";
    $SaveMsgExpense			= "Expense has been saved sucessfully";
    $LoginError				= "Log in failed, Please check your entries.";
    $EmailEmpty				= "Please enter your account email address";
    $PasswordEmpty			= "Please enter your account password";
    $SignUpEmpty			= "All field is require.";
    $PwdNotSame				= "Password values do not match.";
    $SuccessAccount			= "Account has been created successfully, Please " .'<a href="login.php">Login!</a>';
    $AlreadyRegister		= "Account already registered before, Please " .'<a href="login.php">Login!</a>';
    $SuccessAccountUpdate	= "Account has been updated successfully.";
    $DeleteIncome			= "Income has been deleted sucessfully.";
    $DeleteCategory			= "Category has been deleted sucessfully.";
    $SaveMsgCategory		= "Category has been saved sucessfully.";
    $UpdateMsgCategory		= "Category has been updated sucessfully";
    $DeleteAccount			= "Account has been deleted sucessfully.";
    $SaveMsgAccount			= "Account has been saved sucessfully.";
    $UpdateMsgAccount		= "Account has been updated sucessfully";
    $SaveMsgBudget			= "Budget has been saved sucessfully.";
    $AlreadyBudget			= "Sorry! Budget for category has been added before.";
    $DeleteBudget			= "Budget has been deleted sucessfully.";
    $UpdateMsgBudget		= "Budget has been updated sucessfully";
    $DeleteExpense			= "Expense has been deleted sucessfully.";
    $NegativeAmount			= "Negative Amount not allowed.";
    $MessageEmpty			= "Some field is required.";
}
?>
